#!/bin/tcsh
#
# Makes a copy of the MERMAID server and pushes the metadata in
# processed form to the GEOWEB server. This comprises rsyncing,
# VIT2TBL for location organization and VITEXPORT for Web publishing.  
#
# Last input from aetimmes-at-princeton.edu, 10/08/2018
# Last modified by fjsimons-at-alum.mit.edu, 06/12/2026

# Where was I, so I can return to it
set returnto = `pwd`

# Where will all the data be copied TO?
set whereto =  /u/fjsimons/MERMAID/server
set wherest =  /u/fjsimons/MERMAID/sustech
set whereps =  /u/fjsimons/MERMAID/psdmaid
set wherejp =  /u/fjsimons/MERMAID/moby
set whereon =  /u/fjsimons/MERMAID/brazil
set wherees =  /u/fjsimons/MERMAID/unice/eso
set whereku =  /u/fjsimons/MERMAID/unice/kobeuni

# Where will, additionally, all the *.VIT files be copied TO?
set wherevit = /u/fjsimons/MERMAID/serverdata/vitdata
# And where will the *.tbl files go?
set wheretbl = /u/fjsimons/MERMAID/serverdata/tbldata

# Do not mess with SCP as you will need to supply passwords.
# The better solution sets up a CRON job via passwordless
# single-command-use SSH keys. Public keys need to be present
# on the respective servers, and the appropriate range for
# which they are designed needs to be identified using RRSYNC. 
 
# From Princeton at Princeton, we get it all
echo "\nPRINCETON MERMAIDS\n"
# This server is no longer being pushed to but we keep it since contracts changed
# rsync -e "ssh -i /u/fjsimons/.ssh/id_remote_backup" -av mermaid@mermaid.princeton.edu:\*.\* $whereto
# This server is where we now pull from - with one username password
set upass  = `cat /u/fjsimons/EarthScopeOceans/CLS/Preparation/mermaid_iridium-rudics`
lftp -u $upass -e "lcd '$whereto' ; mirror -c -f * ; quit;" sftp://iridium-rudics.cls.fr

# From Stanford at Princeton, we also get it all - this server is no longer being pushed to 
echo "\nSTANFORD MERMAIDS\n"
# This server is no longer being pushed to but we keep it since contracts changed 
# rsync -e "ssh -i /u/fjsimons/.ssh/id_remote_backup" -av psdmaid@mermaid.princeton.edu:\*.\* $whereps
# This server is where we now pull from - with one username and password
set upass  = `cat /u/fjsimons/EarthScopeOceans/CLS/Preparation/psdmaid_iridium-rudics`
lftp -u $upass -e "lcd '$whereps' ; mirror -c -f * ; quit;" sftp://iridium-rudics.cls.fr

# From ESO at GeoAzur at Nice, we used to just get the relevant data (MER, LOG, BIN, cmd, out, vit) into $whereto also
# rsync -e "ssh -i /u/fjsimons/.ssh/id_remote_backup" -av eso@mermaid.unice.fr:\*.[MER,LOG,BIN,cmd,out,vit,...] $whereto
# This server no longer exists, and $whereto no longer contains the data, instead we pull via the new way:
echo "\nESO MERMAIDS\n"
set upass  = `cat /u/fjsimons/EarthScopeOceans/CLS/Preparation/mermaid_taal-unice`
lftp -u $upass -e "lcd '$wherees' ; mirror -c -f eso/*.MER ; mirror -c -f eso/*.LOG ; mirror -c -f eso/*.BIN ; mirror -c -f eso/*.cmd ; mirror -c -f eso/*.out ; mirror -c -f eso/*.vit ; quit;" taal.unice.fr
# From KobeUni at GeoAzur at Nice, we just get the relevant data (MER, LOG, BIN, cmd, out, vit) into $whereto also
#rsync -e "ssh -i /u/fjsimons/.ssh/id_remote_backup" -av kobeuni@mermaid.unice.fr:\*.[MER,LOG,BIN,cmd,out,vit,...] $whereto
# This server no longer exists, and $whereto no longer contains the data, instead we pull via the new way:
echo "\nKOBEUNI MERMAIDS\n"
set upass  = `cat /u/fjsimons/EarthScopeOceans/CLS/Preparation/mermaid_taal-unice`
lftp -u $upass -e "lcd '$whereku' ; mirror -c -f kobeuni/*.MER ; mirror -c -f kobeuni/*.LOG ; mirror -c -f kobeuni/*.BIN ; mirror -c -f kobeuni/*.cmd ; mirror -c -f kobeuni/*.out ; mirror -c -f kobeuni/*.vit ; quit;" taal.unice.fr

# From SUSTECH at Shenzhen, we just get the relevant data - store them separately
echo "\nSUSTECH MERMAIDS\n"
# using rsync command as with Princeton, but the Shenzhen server no longer exists, and no new way

# From JAMSTEC at CLS, we also just get the relevant data - always by LFTP mirror, never RRSYNC
echo "\nJAMSTEC MERMAIDS\n"
# Individual passwords per MERMAID
set floats  = (0056 0057 0101 0102)
foreach float ($floats[*])
    set upass  = `cat /u/fjsimons/EarthScopeOceans/CLS/Preparation/mermaid_$float`
    lftp -u $upass -e "lcd '$wherejp' ; mirror -c -f *.vit ; mirror -c -f *.MER ; mirror -c -f *.BIN ; mirror -c -f *.LOG ; mirror -c -f *.cmd ; mirror -c -f *.out ; mirror -c -f *.S61 ; quit;" sftp://iridium-rudics.cls.fr
end
    
# From OBSERVATORIO NATIONAL at CLS, we just get the relevant data - always by LFTP mirror, never RRSYNC
echo "\nBRAZIL MERMAIDS\n"
# Individual passwords per MERMAID
set floats = (0095 0096 0097 0098 0099 0106 0107 0108)
foreach float ($floats[*])
    set upass = `cat /u/fjsimons/EarthScopeOceans/CLS/Preparation/mermaid_$float`
    lftp -u $upass -e "lcd '$whereon' ; mirror -c -f *.vit ; mirror -c -f *.MER ; mirror -c -f *.BIN ; mirror -c -f *.cmd ; mirror -c -f *.out ; quit;" sftp://iridium-rudics.cls.fr
end

# Then, go into the copied directories and use GIT to ink it in
cd $whereto
git add .
git commit -m "A whole fresh copy made"

cd $wherest
git add .
git commit -m "A whole fresh copy made"

cd $whereps
git add .
git commit -m "A whole fresh copy made"

cd $wherejp
git add .
git commit -m "A whole fresh copy made"

cd $whereon
git add .
git commit -m "A whole fresh copy made"

cd $wherees
git add .
git commit -m "A whole fresh copy made"

cd $whereku
git add .
git commit -m "A whole fresh copy made"

# Then, copy the *vit files separately for extra care
/bin/cp -u $whereto/*.vit $wherevit
/bin/cp -u $wherest/*.vit $wherevit
/bin/cp -u $whereps/*.vit $wherevit
/bin/cp -u $wherejp/*.vit $wherevit
/bin/cp -u $whereon/*.vit $wherevit
/bin/cp -u $wherees/*.vit $wherevit
/bin/cp -u $whereku/*.vit $wherevit

# Make a local backup of that *vit file repository also
cd $wherevit
git add .
git commit -m "A whole fresh copy made"

# Alternative is to use the run_vit2tbl version but then how to pass arguments to it?
setenv LD_LIBRARY_PATH .:$MCRROOT/runtime/glnxa64:$MCRROOT/bin/glnxa64:$MCRROOT/sys/os/glnxa64:$MCRROOT/sys/opengl/lib/glnxa64

# And then these *.vit files need to be converted to *.tbl files via a MATLAB precompiled code
set vitfiles = `ls *.vit`
foreach file ($vitfiles[*])
    echo Processing $wherevit/$file
    # Only changes the extension even though the station names have been uniformly pentadigitized
   /u/fjsimons/PROGRAMS/MFILES/mermaid/vit2tbl $wherevit/$file $wheretbl/$file:r.tbl
end

# Do not forget to unset it!
unsetenv LD_LIBRARY_PATH

# And these *.tbl files then need to be pushed/synced onto GEOWEB using this script
/u/fjsimons/PROGRAMS/UFILES/vitexport

# Return to where I was
cd $returnto
