#!/bin/tcsh
#
# Pushes updated tabled vital files, made by VIT2TBL.M, or its
# runtime-compiled (MCC) version VIT2TBL, to the GEOWEB server
#
# Last input from aetimmes-at-princeton.edu, 10/08/2018
# Last modified by fjsimons-at-alum.mit.edu, 06/26/2026

# Where are these being kept?
set fromwhere = /u/fjsimons/MERMAID/serverdata/tbldata

# Where are these being sent to?
set tothere = /u/fjsimons/MERMAID/serverdata/locdata

# Explicit list of serial numbers:
# -------------------------------------------------------------------------
# owned by GeoAzur    452.020-P-0?    (6-7)
# owned by Princeton  452.020-P-??    (8-13, 16-25)
# owned by Kobe Uni   452.112-N-0?    (1-5)
# owned by SUSTECH    452.020-P-00??  (26-49)
# owned by Kobe Uni   452.020-P-00??  (50, 52-54)
# owned by JAMSTEC    452.020-P-00??  (56-57)
# owned by OSEAN      452.210-P-00??  (14) 
# owned by OSEAN      452.020-P-00??  (51, 64, 84)
# owned by OSEAN      452.120-R-00??  (0, 80, 84)
# owned by Stanford   465.152-R-00??  (1-7 aka B0074-B0080)
# owned by SUSTECH    452.120-R-00??  (58-69, 71-73)
# owned by SUSTECH    452.120-S-00??  (70, 81-82, 85-94)
# owned by OBSNATBR   452.120-T-00??  (95-99)
# owned by JAMSTEC    467.174-T-0???  (0100, 0101)
# owned by JAMSTEC    467.164-T-0???  (0102)
# owned by OBSNATBR   452.120-U-10??  (0106-0108)
#
# -------------------------------------------------------------------------
# 
# Died in service: P-06 since 2025-05-06 Geoazur after being fished up in Fiji
# Died in service: P-07 since 2018-09-11 Geoazur
#
# Died in service: P-08 since 2022-05-14 Princeton after 322 surfacings and  994 SAC files
# Died in service: P-09 since 2023-08-31 Princeton after 350 surfacings and  523 SAC files
# Died in service: P-10 since 2024-12-11 Princeton after                    1302 SAC files
# Died in service: P-11 since 2025-03-17 Princeton after 441 surfacings and  888 SAC files
# Died in service: P-12 since 2024-11-04 Princeton after                     346 SAC files
#                  P-13 
# Died in service: P-16 since 2026-04-02 Princeton after
# Died in service: P-17 since 2025-09-22 Princeton after 338 surfacings and  212 SAC files
#                  P-18
#                  P-19
#                  P-20
#                  P-21
# Died in service: P-22 since 2025-01-09 Princeton after                    1366 SAC files
#                  P-23
# Died in service: P-25 since 2025-10-03 Princeton after 345 surfacings and   90 SAC files
# Died in service: P-24 since 2025-09-16 Princeton after 494 surfacings and  239 SAC files
#
#                  N-01
# Died in service: N-02 since 2024-09-29 JAMSTEC
# Died in service: N-03 since 2019-01-03 JAMSTEC
# Died in service: N-04 since 2025-10-13 JAMSTEC
#                  N-05
#
# Died in service: P-26 since 2025-08-12 SUSTECH
# Died in service: P-27 since 2024-05-06 SUSTECH
# Died in service: P-28 since 2025-08-12 SUSTECH
# Died in service: P-29 since 2025-08-17 SUSTECH
# Died undeployed: P-30 since 2019-08-07 SUSTECH returned to Le Pradet and was retested but not deployed
# Died in service: P-31 since 2025-08-14 SUSTECH
# Died in service: P-32 since 2025-08-15 SUSTECH
# Died in service: P-33 since 2025-08-20 SUSTECH
# Died in service: P-34 since 2019-11-16 SUSTECH
# Died in service: P-35 since 2025-08-18 SUSTECH
# Died in service: P-36 since 2025-08-20 SUSTECH
# Died in service: P-37 since 2025-08-08 SUSTECH
# Died in service: P-38 since 2025-08-12 SUSTECH
# Died in service: P-39 since 2024-04-15 SUSTECH
# Died in service: P-40 since 2025-08-12 SUSTECH
# Died in service: P-41 since 2024-05-23 SUSTECH
# Died in service: P-42 since 2024-03-22 SUSTECH
# Died in service: P-43 since 2022-07-06 SUSTECH
# Died in service: P-44 since 2025-05-31 SUSTECH
# Died in service: P-45 since 2025-02-09 SUSTECH
# Died in service: P-46 since 2025-02-06 SUSTECH
# Died in service: P-47 since 2020-03-28 SUSTECH
# Died in service: P-48 since 2023-04-19 SUSTECH
# Died in service: P-49 since 2024-12-17 SUSTECH
#
# Died in service: P-56 since 2022-01-20 JAMSTEC
# Died undeployed: P-60 since 2020-07-24 SUSTECH

# Died in service: R-01 since 2022-05-11 STANFORD (spectral)
#                  R-02
# Died in service: R-03 since 2026-04-01 STANFORD (spectral) after
#                  R-04
# Died in service: R-05 since 2025-09-22 STANFORD (spectral) after 189 surfacings and 9806 PSD files
# Died in service: R-06 since 2021-10-08 STANFORD (spectral)
#                  R-07

# Died in service: R-50 since 2021-07-26 JAMSTEC (tsunami)
# Died in service: R-52 since 2023-03-02 JAMSTEC
#
# Died in service: R-58 since 2023-05-06 SUSTECH
# Died in service: R-59 since 2023-10-04 SUSTECH
# Died in service: R-63 since 2022-09-21 SUSTECH
# Died in service: P-65 since 2022-05-24 SUSTECH (in Taiwan EEZ)
# Died in service: P-66 since 2023-07-12 SUSTECH (bad deployment)
# Died captively : P-67 since 2022-02-20 SUSTECH (in Philippines EEZ)
# Died in service: R-71 since 2024-01-17 SUSTECH
# Died in service: R-72 since 2024-07-09 SUSTECH
#
# Died in service: T-0100 since 2026-01-05 JAMSTEC (Princeton 4K)
#                  T-0101
# Died in service: T-0102 since 2025-12-13 JAMSTEC (4K)
#
# So... KOBE \ [GEOAZUR] \ PRINCETON \ SUSTECH \ KOBE
#   ... STANFORD \ SUSTECH

# Dead floats: put files now in VITDATA-DEAD / TBLDATA-DEAD / LOCDATA-DEAD
# Dead floats: removing from processing list below, they'll never be touched again

# Remember NOTHING can follow the continuation symbol on the same line...
set lettrs = ( N  N \
               P     P     P  P  P  P     P  P  P \
               P \
               P     P  P  P     P  P \
               R     R     R \
               R  R     R  R  R    R  R  R    R      R   R   R \
               T  T  T  T  T \
               T  T  \
               U  U  U )
# Remember we're trying to capture the two- and four-digits conventions in one loop
# Now you use printf below we get conversion error, but is it inconsequential?
# remove leading zeroes past 7 or bad octals! but kind of need them at the end; so check
set floats = ( 01  05 \
               13    16    18 19 20 21    23 24 25 \
               30 \
               50    52 53 54    56 57 \
               02    04    07 \
               58 59    61 62 63    65 66 67    69    71 72 73 \
               95 96 97 98 99 \
               101 102 \
               106 107 108 )

# Remove the ALL file before making it again - will need to reconsider once we cull the list
/bin/rm -f $tothere/all.txt

# Do them in the loop - watch the treatment of leading zeroes and letters
@ index = 0
foreach float ($floats[*])
     @ index += 1
     set letter = $lettrs[$index]
     # Make the proper float including the leading zero(s)
     set ifloat = `printf "%4.4i" $float`
     # Fix the leading zero issue - not proud of it
     if ( $float == 08 ) then
       set ifloat = 0008
     endif
     if ( $float == 09 ) then
       set ifloat = 0009
     endif
     # Individual floats, last 2*30 lines only
     tail -60    $fromwhere/???.???-$letter-*$float.tbl  >! $tothere/{$letter}{$ifloat}_030.txt
     # Individual floats, complete history
     /bin/cp -f  $fromwhere/???.???-$letter-*$float.tbl     $tothere/{$letter}${ifloat}_all.txt
     # Collective files, only their last line
     tail -1     $fromwhere/???.???-$letter-*$float.tbl >>! $tothere/all.txt
     # Collective files, only their first line, need to do this only once obviously...
     # head -1 -q  $fromwhere/???.???-$letter-*$float.tbl >>! $tothere/misalo.txt
end

# Make the ALL file one that also includes the dead floats without redoing it, obviously

# Then all of those get pushed on to the server via a passwordless
# single-command-use SSH key for back up to a directory that is
# specified via the remote public key by prepending the relevant
# information in the authorized_keys file (for us here it is
# /home/www/people/simons/SOM on geoweb.princeton.edu), so that the
# pushing can be done via CRON without passwords being prompted
# But watch, as in PTON2MARK, to not earlier set any ssh-add key preceding with overriding preference
set finaldest = /home/www/people/simons/SOM
rsync -ve "ssh -i /u/fjsimons/.ssh/id_remote_backup" $tothere/*_030.txt  fjsimons@geoweb.princeton.edu:$finaldest
rsync -ve "ssh -i /u/fjsimons/.ssh/id_remote_backup" $tothere/*_all.txt  fjsimons@geoweb.princeton.edu:$finaldest
rsync -ve "ssh -i /u/fjsimons/.ssh/id_remote_backup" $tothere/all.txt    fjsimons@geoweb.princeton.edu:$finaldest
rsync -ve "ssh -i /u/fjsimons/.ssh/id_remote_backup" $tothere/misalo.txt fjsimons@geoweb.princeton.edu:$finaldest
