#!/bin/tcsh
#
# Pushes tabled vital files, made by VIT2TBL.M, or indeed its
# runtime-compiled (MCC) version VIT2TBL, to the geoweb server
#
# Last input from aetimmes-at-princeton.edu, 10/08/2018
# Last modified by fjsimons-at-alum.mit.edu, 08/08/2019

# Where are these being kept?
set fromwhere = /u/fjsimons/MERMAID/serverdata/tbldata

# Where are these being sent to?
set tothere = /u/fjsimons/MERMAID/serverdata/locdata

# These ones are actually floating! Make an explicit list of the numbers,
# knowing that the name is 452.020-P-??.tbl for Princeton and GeoAzur and 
# the name for Kobe Uni is 452.112-N-??.tbl and the name for the
# floats owned by SUSTC is 452.020-P-????.tbl but in the conversion I
# use P??? for all since the running numbers do not yet overlap 
set floats = (01 02 03 04 05 06 07 08 09 10 11 12 13 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30)

# Remove the ALL file before making it again
/bin/rm -f $tothere/all.txt

# Do them in the loop - watch the treatment of leading zeroes
foreach float ($floats[*])
     # Individual floats, last 2*30 lines only, use P for all of them
     tail -60    $fromwhere/452.???-?-*$float.tbl  >! $tothere/P0{$float}_030.txt
     # Individual floats, complete history, use P for all of them
     /bin/cp -f  $fromwhere/452.???-?-*$float.tbl     $tothere/P0${float}_all.txt
     # Collective files, only their last line
     tail -1      $fromwhere/452.???-?-*$float.tbl >>! $tothere/all.txt
end

# Add the two dead ones back in if we took them out? 

# Then all of those get pushed on to the server via a passwordless
# single-command-use SSH key for back up to a directory that is
# specified via the remote public key by prepending the relevant
# information in the authorized_keys file (for us here it is
# /home/www/people/simons/SOM on geoweb.princeton.edu), so that the
# pushing can be done via CRON without passwords being prompted
rsync -ve "ssh -i /u/fjsimons/.ssh/id_remote_backup" $tothere/*_030.txt fjsimons@geoweb.princeton.edu:
rsync -ve "ssh -i /u/fjsimons/.ssh/id_remote_backup" $tothere/*_all.txt fjsimons@geoweb.princeton.edu:
rsync -ve "ssh -i /u/fjsimons/.ssh/id_remote_backup" $tothere/all.txt   fjsimons@geoweb.princeton.edu:


